[project]
name = "real-estate"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.42.64",
    "dagster==1.5.1",
    "dagster-aws==0.21.1",
    "dagster-pandas==0.21.1",
    "dagster-postgres==0.21.1",
    "dagster-pyspark==0.21.1",
    "dagster-spark==0.21.1",
    "dagster-webserver>=1.5.1",
    "dagstermill>=0.21.1",
    "folium>=0.20.0",
    "ijson>=3.5.0",
    "koalas>=1.8.2",
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "pandas>=3.0.1",
    "pandasql>=0.7.3",
    "pyarrow>=23.0.1",
    "pyspark>=4.1.1",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
]

[project.optional-dependencies]
dev = [
    "dagster-webserver",
    "pytest",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "realestate"

