[project]
name = "real-estate"
version = "0.1.0"
requires-python = ">=3.10,<3.14"
dependencies = [
    "dagster>=1.12,<1.13",
    "dagster-pandas>=0.28,<0.29",
    "dagstermill>=0.28,<0.29",
    "notebook",
    "dagster-aws>=0.28,<0.29",
    "dagster-postgres>=0.28,<0.29",
    "dagster-webserver>=1.12,<1.13",
    "dagster-deltalake>=0.28,<0.29",
    "dagster-deltalake-pandas>=0.28,<0.29",
    "pyarrow",
    "pandas",
    "boto3",
    "pandasql",
    "pyyaml",
    "numpy",
    "seaborn",
    "folium",
    "ijson",
    "scipy",
    "matplotlib",
    "scikit-learn",
    "bs4",
    "jinja2",
    "requests",
    "pyspark",
]

[project.optional-dependencies]
dev = [
    "dagster-webserver>=1.12,<1.13",
    "pytest",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["realestate*"]

[tool.dagster]
module_name = "realestate"

[dependency-groups]
dev = [
    "types-requests>=2.32.4.20260107",
]
