from setuptools import find_packages, setup

setup(
    name="realestate",
    packages=find_packages(exclude=["realestate_tests"]),
    install_requires=[
        "dagster==1.6.8",
        "dagster-pandas",
        "dagstermill",
        "dagster-aws",
        "dagster-postgres",
        "dagster-spark",
        "dagster-pyspark",
        "dagster-webserver",
        #"pyspark==3.5.0",
        "pyspark>=3.5.0; python_version >= '3.8'",
        # "pyspark>=3.0.0; python_version >= '3.8'",
        "pyspark-stubs",
        "pyarrow",
        "pandas",
        "boto3",
        "pandasql",
        "pyyaml",
        "numpy",
        "seaborn",
        "folium",
        "ijson",
        "koalas",
        "scipy",
        "matplotlib",
        "scikit-learn",
        "bs4",
    ],
    extras_require={"dev": ["dagster-webserver", "pytest"]},
)
